var Dice = require("./Dice.js");

var names = undefined;

module.exports.select = function() {
	return names.splice(Dice.rollDX(names.length) - 1, 1)[0];
}

module.exports.Greek = "greek";

module.exports.useTradition = function(tradition) {
	if ("greek" === tradition) {
		names = greekNames.slice(0);
	}
}

var greekNames = [
	{"name": "Aphrodite"},
	{"name": "Apollo"},
	{"name": "Ares"},
	{"name": "Artemis"},
	{"name": "Athena"},
	{"name": "Demeter"},
	{"name": "Dionysos"},
	{"name": "Hades"},
	{"name": "Hephaestus"},
	{"name": "Hera"},
	{"name": "Hermes"},
	{"name": "Hestia"},
	{"name": "Poseidon"},
	{"name": "Zeus"},
	{"name": "Aether"},
	{"name": "Ananke"},
	{"name": "Chaos"},
	{"name": "Chronos"},
	{"name": "Erebos"},
	{"name": "Gaia"},
	{"name": "Hemera"},
	{"name": "Hypnos"},
	{"name": "Nesoi"},
	{"name": "Nyx"},
	{"name": "Uranus"},
	{"name": "Ourea"},
	{"name": "Phanes"},
	{"name": "Pontus"},
	{"name": "Tartarus"},
	{"name": "Thalassa"},
	{"name": "Thanatos"},
	{"name": "Hyperion"},
	{"name": "Iapetus"},
	{"name": "Coeus"},
	{"name": "Crius"},
	{"name": "Cronus"},
	{"name": "Mnemosyne"},
	{"name": "Oceanus"},
	{"name": "Phoebe"},
	{"name": "Rhea"},
	{"name": "Tethys"},
	{"name": "Theia"},
	{"name": "Themis"},
	{"name": "Asteria"},
	{"name": "Astraeus"},
	{"name": "Atlas"},
	{"name": "Aura"},
	{"name": "Dione"},
	{"name": "Eos"},
	{"name": "Epimetheus"},
	{"name": "Eurybia"},
	{"name": "Eurynome"},
	{"name": "Helios"},
	{"name": "Clymene"},
	{"name": "Lelantos"},
	{"name": "Leto"},
	{"name": "Menoetius"},
	{"name": "Metis"},
	{"name": "Ophion"},
	{"name": "Pallas"},
	{"name": "Perses"},
	{"name": "Promotheus"},
	{"name": "Selene"},
	{"name": "Styx"},
	{"name": "Hekatonkheires"},
	{"name": "Agrius"},
	{"name": "Alcyoneus"},
	{"name": "Aloadae"},
	{"name": "Briareus"},
	{"name": "Aigaion"},
	{"name": "Cottus"},
	{"name": "Gyges"},
	{"name": "Otos"},
	{"name": "Ephialtes"},
	{"name": "Antaeus"},
	{"name": "Argus Panoptes"},
	{"name": "Cyclope"},
	{"name": "Arges"},
	{"name": "Brontes"},
	{"name": "Steropes"},
	{"name": "Polyphemus"},
	{"name": "Enceladus"},
	{"name": "Gegenee"},
	{"name": "Geryon"},
	{"name": "Laestrygion"},
	{"name": "Orion"},
	{"name": "Porphyrion"},
	{"name": "Talos"},
	{"name": "Tityos"},
	{"name": "Typhon"}
]